### ISSUE TITLE
Add headers like Content-Security-Policy

### ISSUE THREAD

**Issue by AymericBethencourt** [jkyberneees/restana-static#3]
Hey,

Thanks for this image, I'm really considering using it instead of nginx for my projects! Just one thing, how can you easily add headers like Content-Security-Policy, X-XSS-Protection, X-Content-Type-Options, etc... ?

**Comment by jkyberneees** [comment]
Hi @AymericBethencourt, thanks for liking this project.
At the moment it is not possible to introduce custom middlewares but I will implement this feature so we ca easily cover this and other use cases.

Will get back to you ASAP,
Regards

**Comment by jkyberneees** [comment]
Hi @AymericBethencourt, from v1.1.0 you have the chance to extend the server functionalities through middlewares. Please see:
https://github.com/jkyberneees/restana-static/releases/tag/v1.1.0

Regards
